---
title: "PhotoBioDynamics"
author: "Jannes"
date: "23 11 2020"
output: 
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, fig.showtext = T, 
                      fig.retina = 1)
```

## settings and prep

```{r prep, message=FALSE, warning=FALSE}

# packages
library(tidyverse)
library(sf)
library(rgeos)
library(cowplot)
library(ggspatial)
library(ggtext)
library(patchwork)
library(showtext)
library(here)
library(glue)

# load google fonts
font_add_google("Roboto Mono", "Roboto Mono")
font_add_google("Arvo","Arvo")
font_add_google("Domine", "Domine")
showtext_auto()

# ggplot theme
theme_set(theme_void(base_family = "Arvo"))

theme_update(plot.background = element_rect(fill = "transparent",
                                            color = "transparent"),
             panel.background = element_rect(fill = NA, color = NA),
             plot.title = element_markdown(family = "Arvo",
                                           size = 50,
                                           color = "grey10",
                                           face = "bold",
                                           hjust = .5,
                                           margin = margin(80, 0, 20, 0)),
             plot.subtitle = element_markdown(size = 20,
                                              family = "Domine",
                                              color = "grey30",
                                              face = "plain",
                                              hjust = .5,
                                              lineheight = 1.2,
                                              margin = margin(20, 0, -15, 0)),
             plot.caption = element_text(family = "Arvo",
                                         size = 18,
                                         color = "grey70",
                                         face = "bold",
                                         hjust = .5,
                                         margin = margin(0, 0, 30, 0)),
             plot.title.position = "plot",
             plot.caption.position = "plot",
             plot.margin = margin(10, 0, 10, 0))


# utility fun multiple scales 
new_scale <- function(new_aes) {
  structure(ggplot2::standardise_aes_names(new_aes), class = "new_aes")
}

```

## Data read and prep

```{r data prep}
# get special NaturalEathdata (https://www.naturalearthdata.com) not included in RNaturalEarthData package
path_originaldata = .downloadSpecialNaturalEarhData()

GPP_ras = readRDS(here::here("data", "output", "pp_GPP_ras.Rds"))
NPP_ras = readRDS(here::here("data", "output", "pp_NPP_ras.Rds"))
# bounding box for masking rasters, etc.
bb_poly = st_read(paste0(path_originaldata, 
                         "/orig/naturalearthdata/ne_50m_wgs84_bounding_box.shp")
                  ) %>% 
  st_as_sf() %>%
  # st_crop(., st_bbox(extent(-180,180,-84.35156,90))) %>%    
  st_transform(crs = "+proj=robin")

GPP_annual_ras <- stackApply(GPP_ras,
                         indices = rep(1:12,times = nlayers(GPP_ras)/12),
                         fun = mean, na.rm = TRUE) %>% 
  projectRaster(., crs=crs("+proj=robin")) %>% 
  mask(., bb_poly) 
GPP_annual_ras[is.nan(GPP_annual_ras)] = NA

# GPP seasonal plots (means over season month across time series)
GPP_winter_ras <- mean(GPP_annual_ras[[1:3]], na.rm = TRUE)
GPP_spring_ras <- mean(GPP_annual_ras[[4:6]], na.rm = TRUE)
GPP_summer_ras <- mean(GPP_annual_ras[[7:9]], na.rm = TRUE)
GPP_fall_ras <- mean(GPP_annual_ras[[10:12]], na.rm = TRUE)


# GPP mean of all rasters for large biome GPP map
GPP_mean = GPP_ras[[dim(GPP_ras)[3]:(dim(GPP_ras)[3]-11)]] %>% 
  # crop(., extent(-180,180,-84.35156,90)) %>% 
  mean(na.rm=T) 

# exclude boundary values since not covered by biome polygons in map
GPP_mean_boundaries = boundaries(GPP_mean, type="outer") %>% 
  setValues(.,0, index=!is.na(.))

# exclude repeating raster elements (Alaska, Russia) in Robinson projections
GPP_mean <-   mean(GPP_mean, GPP_mean_boundaries, na.rm = TRUE) %>%
  projectRaster(., crs=crs("+proj=robin")) %>% 
  mask(., bb_poly)

GPP_mean[is.nan(GPP_mean)] = NA


# prepare time series data
GPP_tsdat = readRDS(here::here("data", "output", "globalTS_GPP-NPP.Rds"))
GPP_biomes_ts = readRDS(here::here("data", "output", 
                                   "biomeTS_GPP-NPP.Rds"))[,,1] %>% 
 `colnames<-`(biome_names$BIOME)

dates <- rownames(GPP_tsdat) %>% 
  paste0(. ,"-",1:12) %>% 
  lubridate::ymd(truncated=1)

# extract past ten years of global GPP time serie
GPP_df = data.frame("date" = dates, GPP_tsdat) %>%
  tibble() %>% 
  select(date, GPP, NPP) %>%
  filter(date > as.Date("2008-12-31") & date < as.Date("2019-12-31")) %>% 
  gather(key = "variable", value = "value", -date)
  
# same for biome GPP time series
GPP_biomes_df = data.frame("date" = dates, GPP_biomes_ts) %>%
  tibble() %>% 
  select(date,  everything()) %>%
  filter(date > as.Date("2018-12-31") & date < as.Date("2019-12-31")) %>% 
  gather(key = "variable", value = "value", -date) %>% 
  mutate(variable = gsub("X","",variable))

# use 30 degree graticule for map overlay
grat_poly = st_read(paste0(path_originaldata, 
                         "/orig/naturalearthdata/ne_50m_graticules_30.shp")) %>% 
  st_as_sf() %>% 
  # st_crop(., st_bbox(extent(-180,180,-60.05,90))) %>%     
  st_transform(crs = "+proj=robin") %>% 
  st_intersection(ne_ocean)
  
# 60 degree version for small map plots
grat_poly_60s <- filter(grat_poly, degrees %in% seq(from = 0,to = 180, by = 60))

# land-ocean boundaries
ne_ocean = st_read(paste0(path_originaldata, 
                         "/orig/naturalearthdata/ne_50m_ocean.shp")) %>% 
  st_as_sf() %>%
  st_transform(crs = "+proj=robin")

# biome values, names and assigned colors
biome_names <- 
  list(c(1:14,98,99),
       c("Trop. and Subtrop. Moist Broadleaf Forests", 
         "Trop. and Subtrop. Dry Broadleaf Forests" ,
         "Trop. and Subtrop. Coniferous Forests", 
         "Temperate Broadleaf and Mixed Forests", 
         "Temperate Conifer Forests", 
         "Boreal Forests/Taiga", 
         "Trop. and Subtrop. Grasslands, Savannas and Shrub",
         "Temperate Grasslands, Savannas and Shrub", 
         "Flooded Grasslands and Savannas", 
         "Montane Grasslands and Shrublands", 
         "Tundra", 
         "Med. Forests, Woodlands and Scrub", 
         "Deserts and Xeric Shrub", 
         "Mangroves", 
         "Inland Water", 
         "Rock and Ice"),
       c("darkgreen",
         "orange",
         "chocolate4",
         "yellowgreen",
         "purple",
         "violetred4",
         "lawngreen",
         "yellow4",
         "lightseagreen",
         "darkred",
         "slategray3",
         "tomato",
         "yellow",
         "darkcyan",
         "royalblue",
         "grey30")
     ) %>% as.data.frame(col.names=c("BIOME", "NAME", "COLOR"))

# as named vector (required for color association in scale functions)   
biome_colors <- setNames(as.character(biome_names$COLOR), biome_names$BIOME)  
biome_labels <- setNames(as.character(biome_names$NAME), biome_names$BIOME)  


# get biome shapefile and assign biomes info
biomes = sf::st_read(here::here("data","input","static",
                                "14_biomes_poly.shp")) %>%
  st_as_sf() %>% 
  `st_crs<-`("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0") %>% 
  sf::st_transform(crs = "+proj=robin") %>% 
  merge(y = biome_names)
         

```

## GPP seasons raster map

```{r GPP annual}

seasons <- c("winter","spring","summer","fall")

for (season in seasons){

  GPP_season <-
    get(paste0("GPP_", season, "_ras")) %>% 
    layer_spatial(., aes(alpha = stat(band1)),
                fill="#4e8863",
                interpolate=TRUE) %>% 
    assign(x = paste0("GPP_", season),value = ., inherits = TRUE)
    
}
  
GPP_annual <-
  ggplot() +
  scale_alpha_continuous(na.value = 0, range=c(0,1), guide="none",
                         breaks =seq(0, 100, by = 20)) +
  
  geom_sf(data=ne_ocean, 
          aes(geometry = geometry),
          fill=NA,
          alpha = 0.7,
          color = "grey50", 
          size = 0.5) +
   
  geom_sf(data=grat_poly_60s, 
          aes(geometry = geometry),
          fill=NA,
          color = "grey50", 
          size = 0.5) +

  geom_sf(data=bb_poly, 
          aes(geometry = geometry),
          fill=NA,
          color = "grey50", 
          size = 0.5) +

  theme_void() +
  theme(plot.title = element_text(family = "Roboto Mono", hjust=0.5,
                                   size = 18, color = "grey25"),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(family = "Roboto Mono",
                                   size = 12, color = "grey40"))


```

## raster map plot of GPP and biomes distribution

```{r map}


biome_sf <- 
 geom_sf(data=biomes, 
         aes(geometry = geometry,
             fill=factor(BIOME)),
         color = "grey20", 
         size = 0.5)


GPP_biomes <-
  ggplot() +
  biome_sf +
  scale_fill_manual(values = biome_colors,
                    na.value=0,
                    na.translate=T,
                    name=NULL,
                    labels = biome_names$NAME,
                    guide="none") +
  
  ggnewscale::new_scale_fill()  +
  
  layer_spatial(GPP_mean, 
                aes(alpha = stat(band1)),
                fill="white",
                interpolate=TRUE) +
  scale_alpha_continuous(na.value = 0,range=c(1,0), 
                         name = "Monthly averaged GPP",
                         breaks=seq(0, 100, by = 20),
                         labels = glue::glue(
                           "{seq(0, 100, by = 20)} gC/m <sup>2</sup> ")) +
  
  geom_sf(data=ne_ocean, 
          aes(geometry = geometry),
          fill = NA,
          alpha = 0.7,
          color = "grey50", 
          size = 0.5) +
  geom_sf(data=grat_poly, 
          aes(geometry = geometry),
          fill=NA,
          color = "grey50", 
          size = 0.5) +

  geom_sf(data=bb_poly, 
          aes(geometry = geometry),
          fill=NA,
          color = "grey50", 
          size = 0.5) +
  geom_curve(
    data = tibble(
      x = c(-14065655),
      xend = c(-13065655),
      y = c(-6728945),
      yend = c(-9900000),
    ),
    aes(
      x = x, xend = xend,
      y = y, yend = yend,
    ),
    arrow = arrow(length = unit(0.03, "npc")),
    curvature = 0.45,
    size = 1,
    colour = "grey40",
    linetype = "longdash"
  ) +

  coord_sf(crs="+proj=robin") +
  theme_void() +
  theme(legend.direction = "horizontal",
        legend.position = c(0.5, 1.16),
        legend.box = "horizontal",
        legend.key.height = unit(1, "lines"),
        legend.spacing.x = unit(2, "lines"),
        legend.key.width = unit(6, "lines"),
        legend.key = element_rect(fill="#4e8863",color = "grey40",
                                  linetype = "solid", size = 0.8),
        legend.text = ggtext::element_markdown(family = "Roboto Mono", 
                                               size = 16),
        legend.title = element_text(family = "Arvo", face = "bold", 
                                    color = "grey25", size = 24),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(family = "Roboto Mono",
                                   size = 16, color = "grey40"),
        plot.margin = margin(0, 200, 100, 200)) +

      
  guides(alpha = guide_legend(nrow = 2,
                              title.position = "top", 
                              title.hjust = 0.5,
                              title.vjust = 2,
                              label.position = "bottom"))

```

## 14 biomes legend 

```{r biome scale only}

biome_legend_plot <-
  ggplot() +
  biome_sf +
  scale_fill_manual(values = biome_colors,
                    name = "<span style='color:#4e8863;'><b>Colour scale</b></span> changed by <b>global biomes</b> (Olson et al. 2001):",
                    labels = biome_names$NAME) +
  theme(legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.spacing.x = unit(2, "cm"),
        legend.key.height = unit(0.5, "lines"),
        legend.key = element_rect(color="grey40", fill="grey40"),
        legend.text = element_text(family = "Roboto Mono", size = 14),
        legend.title = element_textbox(family = "Arvo", face = "bold",
                                        hjust = 0.5, color = "grey25", 
                                        size = 24)) +
  guides(fill = guide_legend(nrow = 4,
                             title.position = "top", 
                             title.hjust = .5,
                             title.vjust = -9,
                             label.position = "bottom"))

  
biome_legend <- cowplot::get_legend(biome_legend_plot)

```

## 10 yrs time series GPP, NPP

```{r time series all global}

pals <- c("#4e8863", "#ffc205")

GPP_ts <- 
  ggplot(GPP_df, aes(x = date, y = value)) + 
  geom_area(aes(color = variable, fill= variable),
            alpha = 0.3,
            size=0.7,
            key_glyph = draw_key_timeseries) +
  scale_color_manual(values = pals[1:2],
                     guide = FALSE) +
  scale_fill_manual(values = c("transparent","gold"),
                    guide = FALSE) +
  scale_y_continuous(name=NULL,
                     expand = c(.02, .02),
                     breaks = seq(0, 25, by = 5),
                     labels = glue::glue("{seq(0, 25, by = 5)} GtC ")) +
  scale_x_date(expand = c(.02, .02),
              name=NULL,
              date_labels = "%n %m-%Y", 
              date_breaks = "2 years",
              minor_breaks = NULL) +
  expand_limits(y = c(0,25)) +
  labs(title = "Global <span style='color:#4e8863;'><b>GPP</b></span> & <span style='color:#ffc205;'><b>NPP</b></span> within the past 10 years<br>",x = NULL, 
       y = NULL) +
  theme_void() +
  theme(
    axis.text = element_text(family = "Roboto Mono", size = 14,
                             color = "grey25"),
    axis.text.x = element_text(vjust = -1*2),
    axis.line.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.length.y = unit(5, "pt"),
    axis.ticks.y = element_line(color="grey40"),
    axis.line.y = element_line(color = "grey40"),
    panel.grid.major.x = element_line(color = "grey40",
                                      linetype = "dotted",
                                      size = .4,
                                        ),
    panel.grid.major.y = element_blank(),
    legend.title = element_text(face = "bold", color = "grey80"),
    legend.text = element_text(family = "Roboto Mono", color = "grey55"),
    plot.title =  element_textbox(family = "Arvo", face="bold", hjust=0.5,
                                  size = 24, color = "grey25", vjust=-1),
    plot.margin = margin(20, 100, 20, 100)
  )

```

## intraannual time series GPP of each biome

```{r time series biomes global}

GPP_biome_ts <- 
  ggplot(GPP_biomes_df, aes(x = date, y = value)) + 
  geom_line(aes(color = factor(variable)),
            size=1) +
  geom_curve(
    data = tibble(
      x = c(GPP_biomes_df$date[1] - months(2)),
      xend = c(GPP_biomes_df$date[1] - months(1) + lubridate::days(7)),
      y = c(2.3),
      yend = c(1.85),
    ),
    aes(
      x = x, xend = xend,
      y = y, yend = yend,
    ),
    arrow = arrow(length = unit(0.08, "npc")),
    curvature = 0.45,
    size = 1,
    colour = "grey40",
    linetype = "longdash"
  ) +

  scale_color_manual(values = biome_colors,
                    labels=biome_labels,
                    guide= FALSE) +
  scale_y_continuous(name=NULL,
                     expand = c(.02, .02),
                     breaks = seq(0, 1.5, by = .3),
                     labels = glue::glue("{seq(0, 1.5, by = .3)} GtC ")) +
  scale_x_date(expand = c(.02, .02),
              name=NULL,
              date_labels = "%n %b", 
              date_breaks = "1 months",
              minor_breaks = NULL) +
  coord_cartesian(ylim = c(0, 1.5), xlim = range(GPP_biomes_df$date), 
                  clip="off") +
  expand_limits(y = c(0,1.5)) +
  labs(title = "Each biome's contribution to annual GPP<br>", x = NULL, 
       y = NULL) +
  theme_void() +
  theme(
    axis.text = element_text(family = "Roboto Mono", size = 14,
                             color = "grey25"),
    axis.text.x = element_text(vjust = -1),
    axis.line.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.length.y = unit(5, "pt"),
    axis.ticks.y = element_line(color="grey40"),
    axis.line.y = element_line(color = "grey40"),
    panel.grid.major.x = element_line(color = "grey40",
                                      linetype = "dotted",
                                      size = .4,
                                        ),
    panel.grid.major.y = element_blank(),
    legend.title = element_text(face = "bold", color = "grey80"),
    legend.text = element_text(family = "Roboto Mono", color = "grey55"),
    plot.title = element_textbox(family = "Arvo", face="bold", hjust=0.5,
                              size = 24, color = "grey25"),
    plot.margin = margin(20, 100, 20, 100)

  )


```

##  Cowplot combined panel

```{r plot, fig.width = 16, fig.height = 20}

cowplot::ggdraw(GPP_biomes) +
  draw_image(image = here::here("data", "input","static", 
                                "snowflake.svg"),
             hjust=-1.7, vjust = -26.3, width = 0.03, height = 0.03) +
  draw_plot(GPP_annual + GPP_winter + labs(title = "NH Winter"), hjust=-0.16, 
            vjust = -2, width = 0.3, height = 0.3) +
  draw_image(image = here::here("data", "input","static", "flower.svg"),
             hjust=-7.2, vjust = -31.05, width = 0.03, height = 0.03) +
  draw_plot(GPP_annual + GPP_spring + labs(title = "NH Spring"), hjust=-0.675, 
            vjust = -2.46, width = 0.3, height = 0.3) +
  draw_image(image = here::here("data", "input","static", "sun.svg"), 
             hjust=-25.5, vjust = -31.05, width = 0.03, height = 0.03) +
  draw_plot(GPP_annual + GPP_summer + labs(title = "NH Summer"), hjust=-1.67, 
            vjust = -2.46, width = 0.3, height = 0.3) +
  draw_image(image = here::here("data", "input","static", 
                                "falling-leaves.svg"), 
             hjust=-23, vjust = -19.6, width = 0.04, height = 0.04) +
  draw_plot(GPP_annual + GPP_fall + labs(title = "NH Fall"), hjust = -2.19, 
            vjust = -2, width = 0.3, height = 0.3) +
  draw_plot(biome_legend, vjust = 0.2) +
  draw_plot(GPP_ts, hjust=-0.05, vjust = -0.18, height = 0.18, width = 0.5) +
  draw_plot(GPP_biome_ts, hjust=-0.95, vjust = -0.18, height = 0.18, 
            width = 0.5) +

  plot_annotation(title = "Modelling global biomass dynamics",
                  subtitle = "Photosynthesis is the most important process to assimilate carbon dioxide. By using<br>the solar energy plants generate carbohydrates and thus biomass. The process depends on the intra- and<br>interannual meteorological changes as well as the distribution and composition of global ecosystems. However<br>a distinction must be made between <span style='color:#4e8863;'>Gross Primary Production (<b>GPP</b>)</span> and <span style='color:#ffc205;'>Net Primary Production (<b>NPP</b>)</span>.<br>While GPP accounts for all carbon beeing fixated NPP also accounts for the plants' respiration.<br>Some ecosystems, on the global scale <b>biomes</b>, account for the highest share of GPP/NPP.",
                  caption = "Data preparation, Modelling & Visualization by Jannes Breier  •  Data by NASA (MODIS. CERES) & NOAA (NCDC)")


ggsave(here::here("PhotoBioDynamics.pdf"),
       width = 21, height = 29.7, device = cairo_pdf)

pdftools::pdf_convert(here::here("PhotoBioDynamics.pdf"),
                      format = "png", dpi = 200,
                      antialias = T)
```


***

```{r session-info}
sessionInfo()

```